server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: spring-microservice-1
          uri: http://localhost:8081
          predicates:
            - Path=/microservice1/**
          filters:
            - StripPrefix=1
        - id: spring-microservice-2
          uri: http://localhost:8082
          predicates:
            - Path=/microservice2/**
          filters:
            - StripPrefix=1
        - id: react-app
          uri: http://localhost:3000
          predicates:
            - Path=/react/**
          filters:
            - StripPrefix=1
        - id: node-app
          uri: http://localhost:4000
          predicates:
            - Path=/node/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: gateway
